export const tempPerformanceDataRow = [
    {
        deliveryId: "#NCR8372846246",
        deliverySize: "NP Small Dress",
        logisticsType: "Pickup",
        deliveryDate: "01/01/2023",
        transactionDate: "01/01/2023",
        clientNameFrom: "John Doe",
        clientAddressFrom: "123 Corner Street",
        clientNameTo: "Mary Jane",
        clientAddressTo: "321 Edge Street",
    },
    {
        deliveryId: "#NCR83728462464",
        deliverySize: "NP Small Dress",
        logisticsType: "Pickup",
        deliveryDate: "01/01/2023",
        transactionDate: "01/01/2023",
        clientNameFrom: "John Doe",
        clientAddressFrom: "123 Corner Street",
        clientNameTo: "Mary Jane",
        clientAddressTo: "321 Edge Street",
    },
    {
        deliveryId: "#NCR837284624642",
        deliverySize: "NP Small Dress",
        logisticsType: "Pickup",
        deliveryDate: "01/01/2023",
        transactionDate: "01/01/2023",
        clientNameFrom: "John Doe",
        clientAddressFrom: "123 Corner Street",
        clientNameTo: "Mary Jane",
        clientAddressTo: "321 Edge Street",
    },
    {
        deliveryId: "#NCR8372846246426",
        deliverySize: "NP Small Dress",
        logisticsType: "Pickup",
        deliveryDate: "01/01/2023",
        transactionDate: "01/01/2023",
        clientNameFrom: "John Doe",
        clientAddressFrom: "123 Corner Street",
        clientNameTo: "Mary Jane",
        clientAddressTo: "321 Edge Street",
    },
];